# Generated by Django 5.1.1 on 2024-11-02 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_route_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='tags',
        ),
    ]
