# Generated by Django 5.1.1 on 2024-11-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0003_remove_route_tags'),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='tags',
            field=models.ManyToManyField(to='tag.tag'),
        ),
    ]
