# Generated by Django 5.1.1 on 2024-11-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0008_route_end_route_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='end',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='start',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
